/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconFa6SolidDesktop: typeof import('~icons/fa6-solid/desktop.jsx')['default']
  const IconFa6SolidImages: typeof import('~icons/fa6-solid/images.jsx')['default']
  const IconFa6SolidPenToSquare: typeof import('~icons/fa6-solid/pen-to-square.jsx')['default']
  const IconFa6SolidTrashCan: typeof import('~icons/fa6-solid/trash-can.jsx')['default']
  const IconMdiGithub: typeof import('~icons/mdi/github.jsx')['default']
  const IconTablerLockOpen: typeof import('~icons/tabler/lock-open.jsx')['default']
  const IconTablerLogout2: typeof import('~icons/tabler/logout2.jsx')['default']
  const IconTablerPhotoFilled: typeof import('~icons/tabler/photo-filled.jsx')['default']
  const IconTablerUserSquareRounded: typeof import('~icons/tabler/user-square-rounded.jsx')['default']
}
